version: '3.8'

services:
  frontend:
    build: ./frontend
    expose:
      - "31000"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://backend:8000
      - SECRET_KEY=dev-secret-key
      - ALLOWED_HOSTS=admin.artutos.us.kg
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data:rw
    environment:
      - SECRET_KEY=artutos123
      - ADMIN_EMAIL=admin@artutos.eu.org
      - ADMIN_PASSWORD=artutos123
      - DATA_FILE=/app/data/db.json
      - CORS_ORIGINS=https://admin.artutos.us.kg

  backendE:
    build: ./backendE
    expose:
      - "8001"
    volumes:
      - ./backendE:/app
      - ./data:/app/data:rw
    environment:
      - SECRET_KEY=artutos123
      - DATA_FILE=/app/data/db.json
      - CORS_ORIGINS=*

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
      - backendE